import type { MatchItem, ModelItem, ToolApiItem } from "@/lib/types";

export const mockMatches: MatchItem[] = [
  {
    id: "m-001",
    sport: "basketball",
    league: "NBA",
    matchDate: "2026-04-30",
    startAt: "07:30",
    home: "Celtics",
    away: "Heat",
    venue: "TD Garden",
    status: "ended",
    focusTag: "复盘精选",
    trend: "凯尔特人转换进攻得分占比 21%",
    source: "mock-feed-a",
    analysisReady: true,
  },
  {
    id: "m-002",
    sport: "basketball",
    league: "NBA",
    matchDate: "2026-04-30",
    startAt: "08:00",
    home: "Lakers",
    away: "Warriors",
    venue: "Crypto.com Arena",
    status: "live",
    focusTag: "焦点战",
    trend: "湖人罚球率优势明显，内线冲击强",
    source: "mock-feed-a",
    analysisReady: true,
  },
  {
    id: "m-003",
    sport: "basketball",
    league: "NBA",
    matchDate: "2026-04-30",
    startAt: "10:00",
    home: "Nuggets",
    away: "Suns",
    venue: "Ball Arena",
    status: "upcoming",
    focusTag: "战术博弈",
    trend: "掘金半场阵地效率近5场排名前二",
    source: "mock-feed-a",
    analysisReady: true,
  },
  {
    id: "m-004",
    sport: "basketball",
    league: "CBA",
    matchDate: "2026-04-30",
    startAt: "19:35",
    home: "辽宁",
    away: "广东",
    venue: "辽宁体育馆",
    status: "upcoming",
    focusTag: "强强对话",
    trend: "辽宁主场防守回合压制能力更稳",
    source: "mock-feed-b",
    analysisReady: true,
  },
  {
    id: "m-005",
    sport: "basketball",
    league: "CBA",
    matchDate: "2026-04-30",
    startAt: "20:00",
    home: "浙江",
    away: "新疆",
    venue: "杭州奥体中心",
    status: "live",
    focusTag: "季后赛卡位",
    trend: "浙江外线出手占比持续上升",
    source: "mock-feed-b",
    analysisReady: true,
  },
  {
    id: "m-006",
    sport: "football",
    league: "英超",
    matchDate: "2026-04-30",
    startAt: "21:30",
    home: "Arsenal",
    away: "Liverpool",
    venue: "Emirates Stadium",
    status: "upcoming",
    focusTag: "争冠关键",
    trend: "阿森纳近4场高位逼抢成功率 59%",
    source: "mock-feed-a",
    analysisReady: true,
  },
  {
    id: "m-007",
    sport: "football",
    league: "西甲",
    matchDate: "2026-04-30",
    startAt: "22:15",
    home: "Real Madrid",
    away: "Barcelona",
    venue: "Santiago Bernabeu",
    status: "upcoming",
    focusTag: "国家德比",
    trend: "皇马主场场均预期进球 2.1",
    source: "mock-feed-a",
    analysisReady: true,
  },
  {
    id: "m-008",
    sport: "football",
    league: "德甲",
    matchDate: "2026-04-30",
    startAt: "23:30",
    home: "Bayern",
    away: "Leverkusen",
    venue: "Allianz Arena",
    status: "upcoming",
    focusTag: "榜首大战",
    trend: "勒沃库森反击推进速度更快",
    source: "mock-feed-a",
    analysisReady: true,
  },
  {
    id: "m-009",
    sport: "football",
    league: "欧冠",
    matchDate: "2026-05-01",
    startAt: "02:00",
    home: "Inter",
    away: "PSG",
    venue: "San Siro",
    status: "upcoming",
    focusTag: "淘汰赛",
    trend: "国米定位球防守成功率近10场 84%",
    source: "mock-feed-b",
    analysisReady: true,
  },
  {
    id: "m-010",
    sport: "football",
    league: "欧联",
    matchDate: "2026-05-01",
    startAt: "03:00",
    home: "Roma",
    away: "Sevilla",
    venue: "Stadio Olimpico",
    status: "upcoming",
    focusTag: "次回合",
    trend: "塞维利亚客场控球率明显下降",
    source: "mock-feed-b",
    analysisReady: true,
  },
  {
    id: "m-011",
    sport: "football",
    league: "日职联",
    matchDate: "2026-04-30",
    startAt: "18:00",
    home: "川崎前锋",
    away: "横滨水手",
    venue: "等等力陆上竞技场",
    status: "ended",
    focusTag: "赛后复盘",
    trend: "横滨边路推进成功率 63%",
    source: "mock-feed-b",
    analysisReady: true,
  },
  {
    id: "m-012",
    sport: "football",
    league: "韩K联",
    matchDate: "2026-04-30",
    startAt: "17:30",
    home: "蔚山现代",
    away: "全北现代",
    venue: "蔚山文殊球场",
    status: "ended",
    focusTag: "德比战",
    trend: "蔚山中场夺回球权次数更高",
    source: "mock-feed-b",
    analysisReady: true,
  },
];

export const mockModels: ModelItem[] = [
  {
    id: "mdl-001",
    name: "胜负倾向模型",
    metric: "命中率 71%",
    updateAt: "2026-04-30 10:35",
    confidence: 0.78,
    detail: "结合攻防效率、赛程密度与轮换深度输出倾向建议。",
  },
  {
    id: "mdl-002",
    name: "总分区间模型",
    metric: "区间稳定度 68%",
    updateAt: "2026-04-30 10:33",
    confidence: 0.73,
    detail: "根据节奏、罚球率和失误率估算总分区间。",
  },
  {
    id: "mdl-003",
    name: "首节节奏模型",
    metric: "实时刷新 5min",
    updateAt: "2026-04-30 10:31",
    confidence: 0.69,
    detail: "用于赛中微调，预判开局节奏偏快或偏慢。",
  },
  {
    id: "mdl-004",
    name: "让分穿透模型",
    metric: "回测样本 1200+",
    updateAt: "2026-04-30 10:30",
    confidence: 0.75,
    detail: "综合市场盘口变化与球队攻防差值，评估让分穿透概率。",
  },
  {
    id: "mdl-005",
    name: "伤停影响模型",
    metric: "影响权重实时修正",
    updateAt: "2026-04-30 10:28",
    confidence: 0.72,
    detail: "按球员位置与替代等级，动态量化伤停对胜率和总分的影响。",
  },
  {
    id: "mdl-006",
    name: "冷门预警模型",
    metric: "异常识别率 64%",
    updateAt: "2026-04-30 10:26",
    confidence: 0.66,
    detail: "捕捉盘口异动、舆情偏差与比赛节奏异常，提示潜在冷门风险。",
  },
  {
    id: "mdl-007",
    name: "角球节奏模型",
    metric: "足球专项",
    updateAt: "2026-04-30 10:24",
    confidence: 0.7,
    detail: "针对足球场景，基于边路推进和压迫强度预测角球区间。",
  },
  {
    id: "mdl-008",
    name: "赛后复盘评分模型",
    metric: "评分维度 18 项",
    updateAt: "2026-04-30 10:22",
    confidence: 0.81,
    detail: "对策略执行质量进行多维打分，支持团队复盘迭代。",
  },
];

export const mockTools: ToolApiItem[] = [
  {
    id: "tool-001",
    title: "赛事洞察",
    description: "整合赛程、战绩、伤停与主客场表现，自动生成关键看点。",
    value: "8+ 数据源",
    category: "pre",
  },
  {
    id: "tool-002",
    title: "阵容预测器",
    description: "基于近期出场与教练轮换习惯，生成首发与替补轮换建议。",
    value: "分钟级更新",
    category: "pre",
  },
  {
    id: "tool-003",
    title: "交锋档案",
    description: "聚合历史交手节奏与打法克制关系，给出场景化参考。",
    value: "历史样本 5 年",
    category: "pre",
  },
  {
    id: "tool-004",
    title: "赔率雷达",
    description: "跟踪盘口与赔率波动，识别异常变化并给出风险提示。",
    value: "秒级告警",
    category: "live",
  },
  {
    id: "tool-005",
    title: "赛中节奏面板",
    description: "实时监控节奏、命中率和犯规分布，辅助临场调整。",
    value: "实时流数据",
    category: "live",
  },
  {
    id: "tool-006",
    title: "舆情热度追踪",
    description: "监控社媒和资讯热度变化，识别公众预期偏差。",
    value: "5 分钟采样",
    category: "live",
  },
  {
    id: "tool-007",
    title: "策略工作台",
    description: "将筛选条件沉淀为模板，支持团队共享与版本管理。",
    value: "模板化",
    category: "post",
  },
  {
    id: "tool-008",
    title: "报告生成",
    description: "一键输出赛前简报、赛中播报和赛后复盘。",
    value: "一键导出",
    category: "post",
  },
  {
    id: "tool-009",
    title: "命中率看板",
    description: "统计各策略命中情况，支持按联赛与时间维度对比。",
    value: "多维筛选",
    category: "post",
  },
  {
    id: "tool-010",
    title: "收益曲线回测",
    description: "对历史策略进行回测，输出波动、回撤与收益曲线。",
    value: "可视化回测",
    category: "post",
  },
  {
    id: "tool-011",
    title: "风险分层",
    description: "按联赛、玩法、球队波动率进行分层管理。",
    value: "三级风控",
    category: "post",
  },
  {
    id: "tool-012",
    title: "复盘标签库",
    description: "沉淀高价值复盘标签，提升团队复盘效率与一致性。",
    value: "可复用标签",
    category: "post",
  },
];
