export type ToolCategory =
  | "file-tools"
  | "text-tools"
  | "date-time"
  | "converters"
  | "health";

export type ToolItem = {
  slug: string;
  name: string;
  summary: string;
  category: ToolCategory;
  keyword: string;
};

export const categoryLabels: Record<ToolCategory, string> = {
  "file-tools": "File Tools",
  "text-tools": "Text Tools",
  "date-time": "Date & Time",
  converters: "Converters",
  health: "Health",
};

export const tools: ToolItem[] = [
  {
    slug: "image-compressor",
    name: "Image Compressor",
    summary: "Compress JPG, PNG, and WebP files in seconds.",
    category: "file-tools",
    keyword: "image compressor",
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    summary: "Upload once and convert to JPG, PNG, or WebP instantly.",
    category: "file-tools",
    keyword: "image converter",
  },
  {
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    summary: "Convert iPhone HEIC or HEIF photos to JPG in your browser.",
    category: "file-tools",
    keyword: "heic to jpg",
  },
  {
    slug: "webp-to-jpg",
    name: "WebP to JPG",
    summary: "Convert WebP files to JPG or PNG for broader compatibility.",
    category: "file-tools",
    keyword: "webp to jpg",
  },
  {
    slug: "remove-background",
    name: "Remove Background",
    summary: "Remove simple image backgrounds and export transparent PNG or WebP.",
    category: "file-tools",
    keyword: "remove background",
  },
  {
    slug: "gif-compressor",
    name: "GIF Compressor",
    summary: "Compress animated GIF files by adjusting FPS, size, and color depth.",
    category: "file-tools",
    keyword: "gif compressor",
  },
  {
    slug: "gif-to-mp4",
    name: "GIF to MP4",
    summary: "Convert GIF animations to MP4 for better performance and compatibility.",
    category: "file-tools",
    keyword: "gif to mp4",
  },
  {
    slug: "mp4-to-gif",
    name: "MP4 to GIF",
    summary: "Convert short MP4 clips to GIF for social sharing and docs.",
    category: "file-tools",
    keyword: "mp4 to gif",
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    summary: "Resize by dimensions or target size for social and web.",
    category: "file-tools",
    keyword: "image resizer",
  },
  {
    slug: "image-mosaic",
    name: "Image Mosaic",
    summary: "Generate full-image mosaic effect with adjustable block size and download.",
    category: "file-tools",
    keyword: "image mosaic",
  },
  {
    slug: "old-photo-restoration",
    name: "Old Photo Restoration",
    summary: "Repair faded vintage photos with noise cleanup, scratch reduction, and color recovery.",
    category: "file-tools",
    keyword: "old photo restoration",
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG",
    summary: "Convert PNG files to JPG with custom quality and background color.",
    category: "file-tools",
    keyword: "png to jpg",
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG",
    summary: "Convert JPG images to PNG format in your browser.",
    category: "file-tools",
    keyword: "jpg to png",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    summary: "Convert PDF pages into high-quality JPG images.",
    category: "file-tools",
    keyword: "pdf to jpg",
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    summary: "Convert JPG, PNG, or WebP images into a clean multi-page PDF in your browser.",
    category: "file-tools",
    keyword: "jpg to pdf",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    summary: "Reduce PDF file size online for uploads, email, and faster document sharing.",
    category: "file-tools",
    keyword: "compress pdf",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    summary: "Extract selected PDF pages into a new document using simple page ranges.",
    category: "file-tools",
    keyword: "split pdf",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    summary: "Rotate all pages or selected page ranges in a PDF and download the corrected file.",
    category: "file-tools",
    keyword: "rotate pdf",
  },
  {
    slug: "delete-pdf-pages",
    name: "Delete PDF Pages",
    summary: "Remove selected pages from a PDF and download the cleaned document.",
    category: "file-tools",
    keyword: "delete pdf pages",
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    summary: "Extract readable text from a PDF and copy or download it as plain text.",
    category: "file-tools",
    keyword: "pdf to text",
  },
  {
    slug: "add-watermark-pdf",
    name: "Add Watermark to PDF",
    summary: "Add text watermarks to every page in a PDF and download the marked file.",
    category: "file-tools",
    keyword: "watermark pdf",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    summary: "Combine multiple PDF files into one document.",
    category: "file-tools",
    keyword: "merge pdf",
  },
  {
    slug: "pdf-summarizer",
    name: "PDF Summarizer",
    summary: "Upload a PDF and generate a fast summary with key points.",
    category: "file-tools",
    keyword: "pdf summarizer",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    summary: "Convert .xlsx or .csv sheets into paginated PDF files in your browser.",
    category: "file-tools",
    keyword: "excel to pdf",
  },
  {
    slug: "hairstyle-try-on",
    name: "Hairstyle Try-On",
    summary: "Upload a portrait and preview different hairstyles and hair colors quickly.",
    category: "file-tools",
    keyword: "hairstyle try on",
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    summary: "Count words, characters, and reading time instantly.",
    category: "text-tools",
    keyword: "word counter",
  },
  {
    slug: "character-counter",
    name: "Character Counter",
    summary: "Fast character count for posts, ads, and forms.",
    category: "text-tools",
    keyword: "character counter",
  },
  {
    slug: "emoji-catalog",
    name: "Emoji Catalog",
    summary: "Explore emojis by category, search by keyword, and copy in one click.",
    category: "text-tools",
    keyword: "emoji list",
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    summary: "Switch to lower, upper, title, or sentence case.",
    category: "text-tools",
    keyword: "case converter",
  },
  {
    slug: "remove-line-breaks",
    name: "Remove Line Breaks",
    summary: "Clean pasted text and remove extra line breaks quickly.",
    category: "text-tools",
    keyword: "remove line breaks",
  },
  {
    slug: "id-list-formatter",
    name: "ID List Formatter",
    summary: "Append commas or custom suffix symbols to IDs line by line.",
    category: "text-tools",
    keyword: "id list formatter",
  },
  {
    slug: "md5-tool",
    name: "MD5 Tool",
    summary: "Generate and verify MD5 hashes for text inputs.",
    category: "text-tools",
    keyword: "md5 generator",
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    summary: "Create customizable QR codes from text or links and download as PNG.",
    category: "text-tools",
    keyword: "qr code generator",
  },
  {
    slug: "company-lookup-navigator",
    name: "Company Lookup Navigator",
    summary: "Search official and commercial business databases from one input.",
    category: "text-tools",
    keyword: "company lookup",
  },
  {
    slug: "roblox-player-lookup",
    name: "Roblox Player Lookup",
    summary: "Find public Roblox player profile details by username or user ID.",
    category: "text-tools",
    keyword: "roblox player lookup",
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    summary: "Calculate exact age from a date of birth.",
    category: "date-time",
    keyword: "age calculator",
  },
  {
    slug: "days-between-dates",
    name: "Days Between Dates",
    summary: "Find the exact number of days between any two dates.",
    category: "date-time",
    keyword: "days between dates",
  },
  {
    slug: "days-from-today",
    name: "Days From Today Calculator",
    summary: "Add or subtract calendar or business days from any date instantly.",
    category: "date-time",
    keyword: "days from today",
  },
  {
    slug: "time-zone-converter",
    name: "Time Zone Meeting Planner",
    summary: "Find overlap meeting windows across U.S. and global time zones.",
    category: "date-time",
    keyword: "time zone meeting planner",
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    summary: "Convert length, weight, temperature, and area units.",
    category: "converters",
    keyword: "unit converter",
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    summary: "Calculate percentages, increase, and decrease easily.",
    category: "converters",
    keyword: "percentage calculator",
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    summary: "Split bills and calculate tip by percentage.",
    category: "converters",
    keyword: "tip calculator",
  },
  {
    slug: "loan-payment-calculator",
    name: "Loan Payment Calculator",
    summary: "Estimate monthly payment, total interest, and total repayment.",
    category: "converters",
    keyword: "loan payment calculator",
  },
  {
    slug: "paycheck-calculator",
    name: "Paycheck Calculator",
    summary: "Estimate gross pay, taxes, and take-home pay for each paycheck.",
    category: "converters",
    keyword: "paycheck calculator",
  },
  {
    slug: "time-card-calculator",
    name: "Time Card Calculator",
    summary: "Track weekly work hours, overtime, and gross pay from clock-in entries.",
    category: "converters",
    keyword: "time card calculator",
  },
  {
    slug: "sales-tax-calculator",
    name: "Sales Tax Calculator",
    summary: "Calculate tax amount, pre-tax price, and final total in seconds.",
    category: "converters",
    keyword: "sales tax calculator",
  },
  {
    slug: "discount-tax-calculator",
    name: "Discount + Tax Calculator",
    summary: "Apply discount first, then calculate sales tax and final checkout total.",
    category: "converters",
    keyword: "discount tax calculator",
  },
  {
    slug: "apr-calculator",
    name: "APR Calculator",
    summary: "Estimate annual percentage rate or monthly payment for a fixed-term loan.",
    category: "converters",
    keyword: "apr calculator",
  },
  {
    slug: "subscription-waste-finder",
    name: "Subscription Waste Finder",
    summary: "Upload CSV and detect recurring charges, duplicates, and possible wasted spend.",
    category: "converters",
    keyword: "subscription waste finder",
  },
  {
    slug: "subscription-downgrade-optimizer",
    name: "Subscription Downgrade Optimizer",
    summary: "Model ad tiers, annual plans, and bundles to cut recurring subscription costs.",
    category: "converters",
    keyword: "subscription downgrade optimizer",
  },
  {
    slug: "quarterly-tax-safe-pay-planner",
    name: "Quarterly Tax Safe-Pay Planner",
    summary: "Estimate quarterly tax payments and due-date targets for freelancers and side income.",
    category: "converters",
    keyword: "quarterly tax planner",
  },
  {
    slug: "ev-charging-cost-calculator",
    name: "EV Charging Cost Calculator",
    summary: "Estimate EV charging costs by U.S. state with home/public mix and gas comparison.",
    category: "converters",
    keyword: "ev charging cost calculator",
  },
  {
    slug: "ev-trip-charging-cost-planner",
    name: "EV Trip Charging Cost Planner",
    summary: "Estimate charging stops, charging time, and trip cost for long-distance EV travel.",
    category: "converters",
    keyword: "ev trip charging cost planner",
  },
  {
    slug: "ev-charge-time-estimator",
    name: "EV Charge Time Estimator",
    summary: "Estimate charging time and charging cost from start SoC to target SoC.",
    category: "converters",
    keyword: "ev charge time estimator",
  },
  {
    slug: "ev-home-charger-payback-calculator",
    name: "EV Home Charger Payback Calculator",
    summary: "Estimate Level 2 charger payback period using home/public charging mix and local rates.",
    category: "converters",
    keyword: "ev home charger payback calculator",
  },
  {
    slug: "ev-battery-degradation-estimator",
    name: "EV Battery Degradation Estimator",
    summary: "Forecast EV battery health and expected range decline by usage and climate profile.",
    category: "converters",
    keyword: "ev battery degradation estimator",
  },
  {
    slug: "markup-margin-calculator",
    name: "Markup & Margin Calculator",
    summary: "Calculate selling price, markup, margin, and profit from cost data.",
    category: "converters",
    keyword: "markup margin calculator",
  },
  {
    slug: "ib-buying-power-simulator",
    name: "IB Buying Power Simulator",
    summary: "Estimate remaining stock buying power from A/B/C positions under simplified margin assumptions.",
    category: "converters",
    keyword: "ib buying power calculator",
  },
  {
    slug: "options-breakeven-pl-calculator",
    name: "Options Breakeven & P/L Calculator",
    summary: "Calculate call/put breakeven and expiration profit or loss for single-leg option positions.",
    category: "converters",
    keyword: "options profit calculator",
  },
  {
    slug: "covered-call-return-calculator",
    name: "Covered Call Return Calculator",
    summary: "Estimate premium income, called-away return, breakeven, and annualized yield for covered calls.",
    category: "converters",
    keyword: "covered call calculator",
  },
  {
    slug: "cash-secured-put-yield-calculator",
    name: "Cash-Secured Put Yield Calculator",
    summary: "Calculate cash-secured put premium yield, breakeven, assignment basis, and annualized return.",
    category: "converters",
    keyword: "cash secured put calculator",
  },
  {
    slug: "currency-converter",
    name: "Currency Converter",
    summary: "Convert between USD, EUR, GBP, CAD, AUD, JPY, and CNY.",
    category: "converters",
    keyword: "currency converter",
  },
  {
    slug: "periodic-table",
    name: "Periodic Table",
    summary: "Browse all chemical elements with search, family filters, and quick element details.",
    category: "converters",
    keyword: "periodic table",
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    summary: "Estimate body mass index using height and weight.",
    category: "health",
    keyword: "bmi calculator",
  },
  {
    slug: "tdee-calculator",
    name: "TDEE Calculator",
    summary: "Estimate daily calories based on activity level.",
    category: "health",
    keyword: "tdee calculator",
  },
  {
    slug: "water-intake-calculator",
    name: "Water Intake Calculator",
    summary: "Estimate daily water needs in cups or liters.",
    category: "health",
    keyword: "water intake calculator",
  },
];

export const categoryOrder: ToolCategory[] = [
  "file-tools",
  "text-tools",
  "date-time",
  "converters",
  "health",
];

export function getToolBySlug(slug: string): ToolItem | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): ToolItem[] {
  return tools.filter((tool) => tool.category === category);
}
