export type StateRate = { code: string; name: string; rate: number };

export const US_STATE_ELECTRICITY_RATES: StateRate[] = [
  { code: "AL", name: "Alabama", rate: 0.15 },
  { code: "AK", name: "Alaska", rate: 0.23 },
  { code: "AZ", name: "Arizona", rate: 0.14 },
  { code: "AR", name: "Arkansas", rate: 0.13 },
  { code: "CA", name: "California", rate: 0.30 },
  { code: "CO", name: "Colorado", rate: 0.15 },
  { code: "CT", name: "Connecticut", rate: 0.24 },
  { code: "DE", name: "Delaware", rate: 0.16 },
  { code: "DC", name: "District of Columbia", rate: 0.18 },
  { code: "FL", name: "Florida", rate: 0.15 },
  { code: "GA", name: "Georgia", rate: 0.14 },
  { code: "HI", name: "Hawaii", rate: 0.41 },
  { code: "ID", name: "Idaho", rate: 0.11 },
  { code: "IL", name: "Illinois", rate: 0.16 },
  { code: "IN", name: "Indiana", rate: 0.14 },
  { code: "IA", name: "Iowa", rate: 0.13 },
  { code: "KS", name: "Kansas", rate: 0.14 },
  { code: "KY", name: "Kentucky", rate: 0.13 },
  { code: "LA", name: "Louisiana", rate: 0.12 },
  { code: "ME", name: "Maine", rate: 0.20 },
  { code: "MD", name: "Maryland", rate: 0.16 },
  { code: "MA", name: "Massachusetts", rate: 0.23 },
  { code: "MI", name: "Michigan", rate: 0.19 },
  { code: "MN", name: "Minnesota", rate: 0.16 },
  { code: "MS", name: "Mississippi", rate: 0.13 },
  { code: "MO", name: "Missouri", rate: 0.13 },
  { code: "MT", name: "Montana", rate: 0.13 },
  { code: "NE", name: "Nebraska", rate: 0.12 },
  { code: "NV", name: "Nevada", rate: 0.15 },
  { code: "NH", name: "New Hampshire", rate: 0.20 },
  { code: "NJ", name: "New Jersey", rate: 0.18 },
  { code: "NM", name: "New Mexico", rate: 0.14 },
  { code: "NY", name: "New York", rate: 0.23 },
  { code: "NC", name: "North Carolina", rate: 0.14 },
  { code: "ND", name: "North Dakota", rate: 0.12 },
  { code: "OH", name: "Ohio", rate: 0.15 },
  { code: "OK", name: "Oklahoma", rate: 0.12 },
  { code: "OR", name: "Oregon", rate: 0.14 },
  { code: "PA", name: "Pennsylvania", rate: 0.17 },
  { code: "RI", name: "Rhode Island", rate: 0.22 },
  { code: "SC", name: "South Carolina", rate: 0.15 },
  { code: "SD", name: "South Dakota", rate: 0.13 },
  { code: "TN", name: "Tennessee", rate: 0.13 },
  { code: "TX", name: "Texas", rate: 0.14 },
  { code: "UT", name: "Utah", rate: 0.12 },
  { code: "VT", name: "Vermont", rate: 0.20 },
  { code: "VA", name: "Virginia", rate: 0.14 },
  { code: "WA", name: "Washington", rate: 0.12 },
  { code: "WV", name: "West Virginia", rate: 0.14 },
  { code: "WI", name: "Wisconsin", rate: 0.17 },
  { code: "WY", name: "Wyoming", rate: 0.12 },
];

